# Generated by Django 2.1.7 on 2019-03-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='a', max_length=50)),
                ('way', models.CharField(default='a', max_length=50, null=True)),
                ('Street_number', models.IntegerField(default='a', null=True)),
                ('zip', models.IntegerField(default='a', null=True)),
                ('city', models.CharField(default='a', max_length=50, null=True)),
                ('country', models.CharField(default='a', max_length=50, null=True)),
                ('byScrapy', models.BooleanField(default='a')),
            ],
            options={
                'verbose_name': 'address',
                'ordering': ['zip'],
            },
        ),
    ]
